python classification/train.py \
    --train_paths "./data/train.npz" \
    --generator_train_paths "./data/generate_data.npz"\
    --npz_result_val "./data/val.npz" \
    --npz_result_test "./data/test.npz" \
    --epochs 100 \
    --batch_size 64 \
    --learning_rate 2e-4 \
    --weight_decay 1e-4 \
    --best_model_path "./weight/classification_model_pretrained.pth" \
    --pretrain_path "./pretrain_weight/diffusion_unet.pth" 